Northwind/Northwind.MVC/Controllers/CategoriesController.cs
using Northwind.MVC.Models;
using Northwind.MVC.Service;
using Northwind.Util.Exceptions;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Northwind.MVC.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly CategoriesService _service;
        public CategoriesController()
        {
            this._service = new CategoriesService();
        }
        public ActionResult Index()
        {
            try
            {
                List<CategoriesViewModel> categoriesViews = _service.GetAll();
                return View(categoriesViews);
            }
            catch (MyException ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
        }

        public ActionResult Insert()
        {
            return View("Insert");
        }

        [HttpPost]
        public ActionResult Insert(CategoriesViewModel categoriesViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    throw new MyException("No se pudo agregar la categoria.");
                }
                _service.Insert(categoriesViewModel);
                return RedirectToAction("Index");
            }
            catch (MyException ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
        }

        public ActionResult Edit(int id)
        {
            CategoriesViewModel categoriesViewModel = _service.GetById(id);
            return View("Insert", categoriesViewModel);
        }

        [HttpPost]
        public ActionResult Edit(CategoriesViewModel categoriesViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    throw new MyException("Categoria no encontrada");
                }
                _service.Edit(categoriesViewModel);
                return RedirectToAction("Index");
            }
            catch (MyException ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                _service.Delete(id);
                return Content("1");
            }
            catch (MyException ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

Northwind/Northwind.MVC/Controllers/PublicApiController.cs
using Northwind.MVC.Models;
using Northwind.MVC.Service;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Northwind.MVC.Controllers
{
    public class PublicApiController : Controller
    {
        private readonly PublicApiService _service;
        public PublicApiController() 
        {
            _service = new PublicApiService();
        }
        public async Task<ActionResult> Index(int page)
        {
            try
            {
                ViewBag.CurrentPage = page;
                ResultsViewModel personajes = await _service.GetPageAsync(page);                               
                return View(personajes);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return RedirectToAction("Index", "Error");
            }
            
        }

        public async Task<ActionResult> CharacterProfile(int id)
        {
            try
            {
                PersonajesViewModel personaje = await _service.GetByIDAsync(id);
                return View(personaje);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

Northwind/Northwind.MVC/Controllers/ShippersController.cs
using Northwind.MVC.Models;
using Northwind.MVC.Service;
using Northwind.Util.Exceptions;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Northwind.MVC.Controllers
{
    public class ShippersController : Controller
    {
        private readonly ShippersService _service;
        public ShippersController()
        {
            _service = new ShippersService();
        }

        public ActionResult Index()
        {
            try
            {
                List<ShippersViewModel> shippersView = _service.GetAll();
                return View(shippersView);
            }
            catch (MyException ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
        }

        public ActionResult Insert()
        {
            return View("Insert");
        }

        [HttpPost]
        public ActionResult Insert(ShippersViewModel shippersView)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    throw new MyException("No se pudo agregar el expedidor.");
                }
                _service.Insert(shippersView);
                return RedirectToAction("Index");
            }
            catch (MyException ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
        }

        public ActionResult Edit(int id)
        {
            ShippersViewModel shipperViewModel = _service.GetById(id);
            return View("Insert",shipperViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ShippersViewModel shipperViewModel)
        {
            try
            {
            if (!ModelState.IsValid)
                {
                    throw new MyException("No se pudo editar el expedidor.");
                }
            _service.Edit(shipperViewModel);
            return RedirectToAction("Index");

            }
            catch (MyException ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }

        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                _service.Delete(id);
                return Content("1");
            }
            catch (MyException ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Ha ocurrido un error" + ex.Message;
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

Northwind/Northwind.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title - LabNet</title>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            @Html.ActionLink("LabNet2023", "Index", "Home", null, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">@Html.ActionLink("Inicio", "Index", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Expedidores", "Index", "Shippers", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Categorias", "Index", "Categories", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Rick and Morty API", "Index", "PublicApi", new { page = 1 }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - LabNet - Benjamin Cardozo</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
</body>
</html>